[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "triplyfe"
authors = [{name = "Cleevo", email = "cleevo@gmail.com"}]
dynamic = ["version", "description"]
